
import java.io.Serializable;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alumnogreibd
 */
public class VPrincipal extends javax.swing.JFrame implements Serializable {

    private CallbackClientInterface cliente;
    private CallbackServerInterface servidor;
    private ModeloTablaAmigos mtAmigos = new ModeloTablaAmigos();
    private HashMap<String, CallbackClientInterface> amigosConectados;
    private ArrayList<String> amigos = new ArrayList<>();
    private VChat vc;
    private VSolicitudes vs;
    
    public VPrincipal(CallbackClientInterface cliente, CallbackServerInterface servidor) throws RemoteException, SQLException {
        initComponents();
        this.cliente = new CallbackClientImpl();
        this.servidor = new CallbackServerImpl();
        
        this.cliente = cliente;
        cliente.setVp(this);
        
        this.servidor = servidor;
        
        this.amigos = servidor.obtenerAmigos(cliente.getId(), "");
        this.amigosConectados = servidor.amigosConectados(cliente.getId());
        
        this.mtAmigos = new ModeloTablaAmigos();
        mtAmigos.setFilas(amigos);
        tablaAmigos.setModel(mtAmigos);
        
        btnMensaje.setEnabled(false);
        vc=null;
        vs=null;
        comprobarSolicitud();
        
    }

    public VChat getVc() {
        return vc;
    }
    
    public void setVc(VChat vc) {
        this.vc = vc;
    }

    public VSolicitudes getVs() {
        return vs;
    }

    public void setVs(VSolicitudes vs) {
        this.vs = vs;
    }
    
    public VPrincipal() throws RemoteException{}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buscarAmigotxt = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnSolicitudes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAmigos = new javax.swing.JTable();
        btnMensaje = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        alertaSol = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        jLabel1.setText("Nombre amigo:");

        jLabel2.setText("Lista de Amigos:");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnPerfil.setText("VER PERFIL");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnSolicitudes.setText("SOLICITUDES");
        btnSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudesActionPerformed(evt);
            }
        });

        tablaAmigos.setModel(new ModeloTablaAmigos());
        tablaAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAmigosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAmigos);

        btnMensaje.setText("MANDAR MENSAJE");
        btnMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensajeActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        alertaSol.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        alertaSol.setForeground(new java.awt.Color(255, 51, 51));
        alertaSol.setText("!");

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(31, 31, 31)))
                        .addGap(50, 50, 50)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(buscarAmigotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnBuscar)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(alertaSol, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscarAmigotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnPerfil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnSolicitudes)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(alertaSol)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        try {
            // TODO add your handling code here:
            VUsuarios vu = new VUsuarios(this, true, this.cliente, this.servidor);
            this.setVisible(false);
            vu.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void tablaAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAmigosMouseClicked
        // TODO add your handling code here:
        if(amigosConectados.containsKey(tablaAmigos.getValueAt(tablaAmigos.getSelectedRow(), tablaAmigos.getSelectedColumn()))){
            btnMensaje.setEnabled(true);
        }else{
            btnMensaje.setEnabled(false);
        }
    }//GEN-LAST:event_tablaAmigosMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        try {
            // TODO add your handling code here:
            servidor.unregisterForCallback(cliente.getId());
            System.exit(0);
        } catch (RemoteException | SQLException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalirActionPerformed


    private void btnSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudesActionPerformed
        try {
            // TODO add your handling code here:
            vs = new VSolicitudes(this,true,this.cliente,this.servidor);
            this.setVisible(false);
            vs.setVisible(true);
        } catch (RemoteException | SQLException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //this.setVisible(false);
        
        //this.setVisible(false);
        
    }//GEN-LAST:event_btnSolicitudesActionPerformed

    private void btnMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensajeActionPerformed
        try {
            // TODO add your handling code here:
            vc = new VChat(this, true, this.cliente, this.amigosConectados.get(tablaAmigos.getValueAt(tablaAmigos.getSelectedRow(), tablaAmigos.getSelectedColumn())), this.servidor);
            this.setVisible(false);
            vc.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //this.setVisible(false);
    }//GEN-LAST:event_btnMensajeActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        ModeloTablaAmigos mta = null;
        
        mta = (ModeloTablaAmigos) tablaAmigos.getModel();
        try {
              mta.setFilas(servidor.obtenerAmigos(cliente.getId(), buscarAmigotxt.getText()));
              tablaAmigos.setModel(mta);
              buscarAmigotxt.setText(null);
              btnMensaje.setEnabled(false);
        } catch (RemoteException | SQLException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            // TODO add your handling code here:
            actualizarAmigos();
            comprobarSolicitud();
            servidor.actualizarConectados(cliente.getId());
        } catch (RemoteException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed


    public void nuevoAmigoConectado(CallbackClientInterface cliente, String usuario){
 
            amigosConectados.put(usuario, cliente);
    }
    public void nuevoAmigo(CallbackClientInterface cliente, String usuario){
        amigos.add(usuario);
        mtAmigos=(ModeloTablaAmigos) tablaAmigos.getModel();
        mtAmigos.nuevaFila(usuario);
    }
    
   public void quitarConectado(String amigo){
       if(amigosConectados.containsKey(amigo)){
           amigosConectados.remove(amigo);
       }
   }
   
   public Boolean recibirMensaje(String amigo, String mensaje){
       if(vc!=null){
           vc.recibirMenasje(amigo, mensaje);
           return true;
       }
       return false;
       
   }
   
   public void actualizarAmigos() throws RemoteException, SQLException{
       mtAmigos.setFilas(servidor.obtenerAmigos(cliente.getId(), ""));
       tablaAmigos.setModel(mtAmigos);
   }
   
   public void comprobarSolicitud()throws RemoteException, SQLException{
       if(servidor.solicitudesEntrantes(cliente.getId()).isEmpty()){
            alertaSol.setVisible(false);
        }
        else{
            alertaSol.setVisible(true);
        }
   }
   
           

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertaSol;
    private javax.swing.JToggleButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMensaje;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSolicitudes;
    private javax.swing.JTextField buscarAmigotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAmigos;
    // End of variables declaration//GEN-END:variables
}
