
import java.io.Serializable;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */




/**
 *
 * @author rtato
 */
public class VSolicitudes extends javax.swing.JDialog implements Serializable {

    /**
     * Creates new form VSolicitudes
     */
    
    private VPrincipal padre;
    CallbackClientInterface cliente;
    CallbackServerInterface servidor;
    private ArrayList<String> misSolicitudes = new ArrayList<>();
    private ArrayList<String> solicitudesEnviadas = new ArrayList <>();
    
    public VSolicitudes(java.awt.Frame parent, boolean modal, CallbackClientInterface cliente, CallbackServerInterface servidor) throws RemoteException, SQLException {
        super(parent, modal);
        initComponents();
        this.padre = (VPrincipal)parent;
        this.cliente=cliente;
        this.servidor=servidor;
        this.misSolicitudes = servidor.solicitudesEntrantes(cliente.getId());
        this.solicitudesEnviadas = servidor.misSolicitudes(cliente.getId());
        
        Aceptar.setEnabled(false);
        Denegar.setEnabled(false);
        EliminarSolicitud.setEnabled(false);
        envioSolicitud.setEnabled(false);
        ModeloTablaAmigos m = new ModeloTablaAmigos();
        ModeloTablaAmigos m2 = new ModeloTablaAmigos();
        ModeloTablaAmigos m3 = new ModeloTablaAmigos();
        m.setFilas(misSolicitudes);
        m2.setFilas(solicitudesEnviadas);
        Solicitudes.setModel(m);
        envios.setModel(m2);
        envSolicitudes.setModel(m3);
        aviso1.setVisible(false);
        //this.users = servidor.
        setTitle("Solicitudes");
        //Denegar.setEnabled(false);
        //Aceptar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Solicitudes = new javax.swing.JTable();
        Aceptar = new javax.swing.JToggleButton();
        Denegar = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        envios = new javax.swing.JTable();
        EliminarSolicitud = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        buscaramigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        envioSolicitud = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        envSolicitudes = new javax.swing.JTable();
        aviso1 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fusiones");
        setResizable(false);

        Solicitudes.setModel(new ModeloTablaAmigos());
        Solicitudes.getTableHeader().setReorderingAllowed(false);
        Solicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SolicitudesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Solicitudes);

        Aceptar.setText("Aceptar solicitud");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Denegar.setText("Denegar solicitud");
        Denegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenegarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Denegar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Denegar))
                .addGap(32, 32, 32))
        );

        jTabbedPane2.addTab("Solicitudes entrantes", jPanel1);

        envios.setModel(new ModeloTablaAmigos());
        envios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(envios);

        EliminarSolicitud.setText("Eliminar");
        EliminarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarSolicitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EliminarSolicitud)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EliminarSolicitud)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Solicitudes enviadas", jPanel3);

        buscaramigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaramigoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        envioSolicitud.setText("Enviar solicitud");
        envioSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envioSolicitudActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        envSolicitudes.setModel(new ModeloTablaAmigos());
        envSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                envSolicitudesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(envSolicitudes);

        aviso1.setForeground(new java.awt.Color(255, 51, 51));
        aviso1.setText("TIene que haber un minimo de 3 caracteres");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscaramigo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(aviso1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(envioSolicitud)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(aviso1)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscaramigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(envioSolicitud))
                    .addComponent(jLabel3))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Enviar solicitud", jPanel2);

        refresh.setText("Actualizar");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir)
                .addGap(122, 122, 122))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Salir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(refresh, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Petición fusión");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            padre.actualizarAmigos();
            servidor.actualizarConectados(cliente.getId());
            padre.setVs(null);
            padre.setVisible(true);
            padre.comprobarSolicitud();
            this.dispose();
        } catch (RemoteException | SQLException ex) {
            Logger.getLogger(VSolicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SalirActionPerformed

    private void envioSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envioSolicitudActionPerformed
        // TODO add your handling code here:
        ModeloTablaAmigos m;
        ModeloTablaAmigos m2;
        m = (ModeloTablaAmigos) envSolicitudes.getModel();
        m2 = (ModeloTablaAmigos) envios.getModel();
        try{
            if(!buscaramigo.getText().isEmpty()){
                if(!servidor.existeUsuario(m.obtenerAmigos(envSolicitudes.getSelectedRow()))){
                    if(!servidor.obtenerAmigos(cliente.getId(), "").contains(m.obtenerAmigos(envSolicitudes.getSelectedRow()))){
                        servidor.hacerSolicitud(cliente.getId(), m.obtenerAmigos(envSolicitudes.getSelectedRow()));
                        m.setFilas(new ArrayList<>());
                        envSolicitudes.setModel(m);
                        m2.setFilas(servidor.misSolicitudes(cliente.getId()));
                        envios.setModel(m2);
                        buscaramigo.setText("");
                    }
                    else{
                        //fa.muestraExcepcion("Error: Ya es tu amigo");
                        System.out.println("Error: Ya es tu amigo");
                        return;
                    }
                }
                else{
                    //fa.muestraExcepcion("Error: No existe ese usuario");
                    System.out.println("Error: No existe ese usuario");
                    return;
                }
            }else{
                //fa.muestraExcepcion("Error: Tienes que introducir un nombre");
                System.out.println("Error: Tienes que introducir un nombre");
                return;
            }
        }catch (NumberFormatException e) {
            //fa.muestraExcepcion("Error: El nombre es incorrecto");
            System.out.println("Error: El nombre es incorrecto");
            return;
        } catch (SQLException ex) {
            Logger.getLogger(VSolicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(VSolicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_envioSolicitudActionPerformed

    private void buscaramigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaramigoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buscaramigoActionPerformed

    private void DenegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenegarActionPerformed
        // TODO add your handling code here:
        ModeloTablaAmigos m;
        m = (ModeloTablaAmigos) Solicitudes.getModel();
        try {
            servidor.rechazarSolicitud(m.obtenerAmigos(Solicitudes.getSelectedRow()),cliente.getId());
            m.borrarFila(Solicitudes.getSelectedRow());
        } catch (SQLException ex) {
            Logger.getLogger(VSolicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(VSolicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
        Denegar.setEnabled(false);
        Aceptar.setEnabled(false);
    }//GEN-LAST:event_DenegarActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        ModeloTablaAmigos m;
        m = (ModeloTablaAmigos) Solicitudes.getModel();
        try {
            servidor.aceptarSolicitud1(cliente.getId(), m.obtenerAmigos(Solicitudes.getSelectedRow()));
            servidor.aceptarSolicitud1(m.obtenerAmigos(Solicitudes.getSelectedRow()), cliente.getId());
            servidor.aceptarSolicitud2(cliente.getId(), m.obtenerAmigos(Solicitudes.getSelectedRow()));
            servidor.aceptarSolicitud2(m.obtenerAmigos(Solicitudes.getSelectedRow()), cliente.getId());
            m.borrarFila(Solicitudes.getSelectedRow());
            
        } catch (SQLException ex) {
            Logger.getLogger(VSolicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(VSolicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
        Denegar.setEnabled(false);
        Aceptar.setEnabled(false);
    }//GEN-LAST:event_AceptarActionPerformed

    private void SolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SolicitudesMouseClicked
        // TODO add your handling code here:
        Denegar.setEnabled(true);
        Aceptar.setEnabled(true);
    }//GEN-LAST:event_SolicitudesMouseClicked

    private void buscar(){
         ModeloTablaAmigos m3;
        m3 = (ModeloTablaAmigos) envSolicitudes.getModel();
        m3.setFilas(new ArrayList<>());
        envSolicitudes.setModel(m3);
        try {
            if(buscaramigo.getText().length()>=3){
                ArrayList<String> amigosbuscados = new ArrayList<>();
                amigosbuscados = servidor.buscarUsuariosSolictudes(buscaramigo.getText());
                if(amigosbuscados.contains(this.cliente.getId())){
                    amigosbuscados.remove(this.cliente.getId());
                }
                ArrayList<String> amigoseliminados = new ArrayList<>();
                for(String amig : amigosbuscados){
                    if(servidor.obtenerAmigos(cliente.getId(), "").contains(amig)){
                        amigoseliminados.add(amig);
                    }
                }
                for(String eliminado : amigoseliminados){
                    amigosbuscados.remove(eliminado);
                }
                amigoseliminados.clear();
                ModeloTablaAmigos m4;
                m4 = (ModeloTablaAmigos) envios.getModel();
                for(String amig : m4.devolver()){
                    if(amigosbuscados.contains(amig)){
                        amigoseliminados.add(amig);
                    }
                }
                for(String eliminado : amigoseliminados){
                    amigosbuscados.remove(eliminado);
                }
                m3.setFilas(amigosbuscados);
                aviso1.setVisible(false);
            }
            else{
                aviso1.setVisible(true);
            }
            envioSolicitud.setEnabled(false);
        } catch (SQLException | RemoteException ex) {
            Logger.getLogger(VSolicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void EliminarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarSolicitudActionPerformed
        // TODO add your handling code here:
        ModeloTablaAmigos m3;
        m3 = (ModeloTablaAmigos) envios.getModel();
        try {
            servidor.elminarSolicitud(this.cliente.getId(),m3.obtenerAmigos(envios.getSelectedRow()));
            m3.borrarFila(envios.getSelectedRow());
            EliminarSolicitud.setEnabled(false);
        } catch (SQLException | RemoteException ex) {
            Logger.getLogger(VSolicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EliminarSolicitudActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        ModeloTablaAmigos m;
        ModeloTablaAmigos m2;
        m = (ModeloTablaAmigos) envSolicitudes.getModel();
        m2 = (ModeloTablaAmigos) Solicitudes.getModel();
        try {
            m.setFilas(servidor.solicitudesEntrantes(cliente.getId()));
            m2.setFilas(servidor.misSolicitudes(cliente.getId()));
            
            Solicitudes.setModel(m);
            envios.setModel(m2);
            
            Denegar.setEnabled(false);
            Aceptar.setEnabled(false);
            EliminarSolicitud.setEnabled(false);
        } catch (RemoteException | SQLException ex) {
            Logger.getLogger(VSolicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_refreshActionPerformed

    private void enviosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviosMouseClicked
        // TODO add your handling code here:
        EliminarSolicitud.setEnabled(true);
    }//GEN-LAST:event_enviosMouseClicked

    private void envSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_envSolicitudesMouseClicked
        // TODO add your handling code here:
        envioSolicitud.setEnabled(true);
    }//GEN-LAST:event_envSolicitudesMouseClicked

    public void actualizaTablas() throws RemoteException, SQLException{
         ModeloTablaAmigos m = new ModeloTablaAmigos();
        ModeloTablaAmigos m2 = new ModeloTablaAmigos();
        ModeloTablaAmigos m3 = new ModeloTablaAmigos();
        
        m.setFilas(servidor.solicitudesEntrantes(cliente.getId()));
        m2.setFilas(solicitudesEnviadas);
        Solicitudes.setModel(m);
        envios.setModel(m2);
        envSolicitudes.setModel(m3);
        buscar();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Aceptar;
    private javax.swing.JToggleButton Denegar;
    private javax.swing.JButton EliminarSolicitud;
    private javax.swing.JButton Salir;
    private javax.swing.JTable Solicitudes;
    private javax.swing.JLabel aviso1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTextField buscaramigo;
    private javax.swing.JTable envSolicitudes;
    private javax.swing.JButton envioSolicitud;
    private javax.swing.JTable envios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
