
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nuria Gomez
 */

public class VUsuarios extends javax.swing.JDialog {

 private CallbackClientInterface cliente;
  private CallbackServerInterface servidor;
 private VPrincipal padre;

    /**
     * Creates new form VUsuarios
     */

    public VUsuarios(java.awt.Frame parent, boolean modal, CallbackClientInterface cliente, CallbackServerInterface servidor) throws RemoteException {
        super(parent, modal);
        this.padre=(VPrincipal)parent;
        initComponents();
        this.cliente = new CallbackClientImpl();
        this.servidor = new CallbackServerImpl();
        this.cliente = cliente;
        this.servidor = servidor;
        idtxt.setText(cliente.getId());
        
        avisotxt.setVisible(false);
        aviso2txt.setVisible(false);
        aviso3txt.setVisible(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnGuardarUsuario = new javax.swing.JButton();
        avisotxt = new javax.swing.JLabel();
        aviso2txt = new javax.swing.JLabel();
        claveNuevatxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        clavetxt = new javax.swing.JPasswordField();
        aviso3txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Perfil");
        setResizable(false);

        jLabel3.setText("Id");

        idtxt.setEditable(false);

        jLabel4.setText("Clave Nueva:");

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuardarUsuario.setText("Guardar");
        btnGuardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUsuarioActionPerformed(evt);
            }
        });

        avisotxt.setForeground(new java.awt.Color(255, 51, 51));
        avisotxt.setText("Error: La contraseña es la misma que la ya guardada");

        aviso2txt.setForeground(new java.awt.Color(255, 51, 51));
        aviso2txt.setText("Error: Es necesario introducir una clave");

        jLabel1.setText("Clave Antigua:");

        aviso3txt.setForeground(new java.awt.Color(255, 51, 51));
        aviso3txt.setText("Error: La contraseña antigua no es correcta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aviso3txt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(avisotxt)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardarUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aviso2txt)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(58, 58, 58))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(clavetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                                .addComponent(claveNuevatxt)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clavetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(claveNuevatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(aviso3txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avisotxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aviso2txt)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardarUsuario))
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUsuarioActionPerformed
            //Editar usuario
           if(!(clavetxt.getText().isEmpty() && claveNuevatxt.getText().isEmpty())){
               try {
                   if(cliente.getId().equals(servidor.comprobarAutentificacion(cliente.getId(), clavetxt.getText()))){
                       try {
                           if(!clavetxt.getText().equals(claveNuevatxt.getText())){
                            servidor.actualizarClave(cliente.getId(), claveNuevatxt.getText());
 
                            aviso2txt.setVisible(false);
                            avisotxt.setVisible(false);
                            aviso3txt.setVisible(false);
                            }
                           else{
                               aviso2txt.setVisible(false);
                               avisotxt.setVisible(true);
                               aviso3txt.setVisible(false);
                           }
                       } catch (RemoteException | SQLException ex) {
                           Logger.getLogger(VUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                       }
                   }else{
                       aviso3txt.setVisible(true);
                       aviso2txt.setVisible(false);
                       avisotxt.setVisible(false);
                   }
               } catch (RemoteException ex) {
                   Logger.getLogger(VUsuarios.class.getName()).log(Level.SEVERE, null, ex);
               }
           }else{
               aviso2txt.setVisible(true);
               avisotxt.setVisible(false);
               aviso3txt.setVisible(false);
           }
           
          
    }//GEN-LAST:event_btnGuardarUsuarioActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
     try {
         padre.actualizarAmigos();
         padre.comprobarSolicitud();
         this.dispose();
         padre.setVisible(true);
     } catch (RemoteException ex) {
         Logger.getLogger(VUsuarios.class.getName()).log(Level.SEVERE, null, ex);
     } catch (SQLException ex) {
         Logger.getLogger(VUsuarios.class.getName()).log(Level.SEVERE, null, ex);
     }
        
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso2txt;
    private javax.swing.JLabel aviso3txt;
    private javax.swing.JLabel avisotxt;
    private javax.swing.JButton btnGuardarUsuario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPasswordField claveNuevatxt;
    private javax.swing.JPasswordField clavetxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
   private void habilitarbtnGuardar(){
        if(!clavetxt.getText().isEmpty()&& !idtxt.getText().isEmpty()){
            btnGuardarUsuario.setEnabled(true);
        }else{
             btnGuardarUsuario.setEnabled(false);
        }
    }
   
}






